Adding documentation
whimc/Position-Tracker pull request #11
Opened 2021-09-30 19:33 UTC by EmiCB

Added JavaDoc and some inline comments to all files

2021-10-01 12:58 UTC, jackah2 requested changes
A few minor changes. Everything else looks good :)

2021-10-01 12:58 UTC, jackah2 commented on src/main/java/edu/whimc/positiontracker/sql/Queryer.java
> +        // add data to database if connection exists
```suggestion
        // add data to database asynchronously
```
This is a [try-with statement](https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html) which automatically closes the connection after it's done. Technically the connection doesn't exist at this point.

2021-10-01 12:58 UTC, jackah2 commented on src/main/java/edu/whimc/positiontracker/sql/Queryer.java
> +    /** The formatting for a data insertion. */
```suggestion
    /** SQL query to insert position data. */
```

2021-10-01 12:58 UTC, jackah2 commented on src/main/java/edu/whimc/positiontracker/sql/Queryer.java
> +         * Adds an SQL Insertion with the PositionEntry data.
```suggestion
         * Adds this entry's data to the PreparedStatement's batch.
```

2021-10-01 16:04 UTC, EmiCB commented
Oops, I also forgot to update the readme!

2021-10-07 16:21 UTC, jackah2 approved these changes
Looks good!

2021-10-07 16:21 UTC, jackah2 commented
Resolves #3

2021-10-08 16:04 UTC, merged